name: Learn setup
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-lastest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
    
      - name: Install dependencies
        run: npm i
    
      - name: Build code
        run: npm run build
